name: Upload Website

on:
  push:
    branches: [ main ]


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    deploy:
      runs-on: ubuntu-latest
      steps:
        run: |
          ls

 
