name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build React App
      run: |
        cd Frontend
        npm install && npm run build
        npm install boto3
    - name: Deploy app build to S3 bucket
      run: aws s3 sync ./dist/ s3://bryantconti.com/ --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}